DROP TABLE location    		CASCADE CONSTRAINTS;
DROP TABLE department 		CASCADE CONSTRAINTS;
DROP TABLE employee_n 		CASCADE CONSTRAINTS;
DROP TABLE applicant 		CASCADE CONSTRAINTS;
DROP TABLE document 		CASCADE CONSTRAINTS;
DROP TABLE document_status 	CASCADE CONSTRAINTS;
DROP TABLE document_type 	CASCADE CONSTRAINTS;
DROP TABLE document_route 	CASCADE CONSTRAINTS;

COMMIT;